name: Build Minecraft Mod

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew
        continue-on-error: true

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Build Artifact (.jar)
        uses: actions/upload-artifact@v4
        with:
          name: NSR_Automations-Mod
          path: build/libs/*.jar
